### ISSUE TITLE
Support for secure installation lifecycle

### ISSUE THREAD

**Issue by icecrime** [ShiftLeftSecurity/atlassian-connect-go#5]
As described [on the Atlassian community forums](https://community.developer.atlassian.com/t/action-required-atlassian-connect-installation-lifecycle-security-improvements/49046), an upcoming change will impact Connect Apps' installation flow:

> We are making a breaking change to the Connect app lifecycle events to improve the security of the Connect framework. In the install and uninstall callbacks sent by Atlassian to your app, the Authorization JWT token now includes a new signature that you can use to verify that the request is genuine. The signature is generated using an asymmetric keypair using the RS256 algorithm. **All Jira and Confluence Connect apps will need to opt-in to this change to receive the updated, signed lifecycle hooks**.

At the very minimum, this will require the ability to add an `apiMigrations` section to the app descriptor.

Please let me know if that something that maintainers of the projects intend to work on, or if you are waiting for a community contribution for it! Thank you for your work.

**Comment by icecrime** [comment]
Ping @perrito666 🙏 Thank you!

**Comment by perrito666** [comment]
Ouch really sorry this got drowned in my inbox :( I'll address it over the weekend. Thank you for pinging me

**Comment by perrito666** [comment]
hey, there is a PR for this in https://github.com/ShiftLeftSecurity/atlassian-connect-go/pull/6 please give it a shot if you can @icecrime

**Comment by icecrime** [comment]
Wow thank you! I had _also_ missed this notification, but I'll take a look ASAP :-)

**Comment by perrito666** [comment]
This is fixed by https://github.com/ShiftLeftSecurity/atlassian-connect-go/releases/tag/v0.0.4 (hopefully :D)
